---
galaxy_info:
  author: Sylvain Chen
  description: Configure AWX (Day 1-2) 
  license: BSD
  min_ansible_version: 2.15

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
collections:
- operator_sdk.util
- kubernetes.core
- community.general