
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: awx-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: awx-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: awx-operator.v2.18.0
  config:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "2000Mi"
        cpu: "2000m"
