# permissions for end users to edit awxconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awxconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: awx-config-operator
    app.kubernetes.io/part-of: awx-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: awxconfig-editor-role
rules:
- apiGroups:
  - awx.acme.com
  resources:
  - awxconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - awx.acme.com
  resources:
  - awxconfigs/status
  verbs:
  - get
