---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for awx.acme.com/v1alpha1, Kind: AWXConfig
  ##
  - apiGroups:
      - awx.acme.com
    resources:
      - awxconfigs
      - awxconfigs/status
      - awxconfigs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
  ## Get, list, watch AWX
  - apiGroups:
      - awx.ansible.com
    resources:
      - awxs
#      - automationcontrollers
    verbs:
      - get
      - list
      - watch
  ## Creation of service monitors
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors